version: '2'
services:
  prometheus:
    build: prometheus
    ports:
      - "9090:9090"
  grafana:
    build: grafana
    ports:
      - "3000:3000"
  application:
    build: application
    ports:
      - "8080:8080"